name: getdriveupl

on:
  workflow_dispatch:
    inputs:
      URLID:
        description: 'Drive file ID'
        required: true
        default: ''
      NAME:
        description: 'The name to upload the file to (do not include the extension)'
        required: true
        default: ''
      TYPE:
        description: 'File extention'
        required: true
        type: choice
        options:
        - zip
        - rar
        - tar
        - 7z
        - gzip
        - lz
        - lz4
        - yaml
        - txt
        - docx
        - c
        - cc
        - cpp
        - py
        - java
        - rs
        - php
        - html

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v3

    - name: Setup environment
      run: |
        sudo apt update
        sudo apt install git gh python3 python-pip
        python -m pip install --upgrade pip

    - name: Download file
      run: |
        cd /home
        sudo mkdir gupload && sudo chmod 777 gupload && cd gupload
        pip3 install gdown==2.3.1
        gdown --id ${{ github.event.inputs.URLID }}
        mv * ${{ github.event.inputs.NAME }}.${{ github.event.inputs.TYPE }}

    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: |
          /home/gupload/*.${{ github.event.inputs.TYPE }}
        name: ${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          ${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
